services:
  app.nest:
    build:
      context: .
      dockerfile: apps/app-nest/Dockerfile
    image: ghcr.io/akulllvlllad/top-app:develop
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
